
/* Declaring dependencies and attaching the folders where the external scripts are located*/
const express = require('express'),
  body_parser = require('body-parser'),
  ejs = require('ejs'),
  // browser-detect is to be used to keep the participant awau from using mobile devices
  detect = require('browser-detect'),
  // db.js is where the script responsible for attaching a database is found
  db = require(__dirname+'/controllers/db.js'),
  // helper.js generates a random id for each participant
  helper = require(__dirname+'/libraries/helper.js'),
  tasks = require(__dirname+'/controllers/tasks.js'),
  responses = require(__dirname+'/controllers/responses.js');

// dotenv allows locating .env file with database credentials automatically
require('dotenv').config();

const study_name = 'pilot';
const app = express();
const PORT = process.env.PORT || 5000;

// set the directories for .html files and base jsPsych scripts
app.use(express.static(__dirname + '/public'));
app.set('views', __dirname + '/public/views');
app.use('/jspsych', express.static(__dirname + "/jspsych"));
// failure to include the following results in errors when trying to run the script
app.engine('html', ejs.renderFile);
app.set('view engine', 'html');
app.use('/libraries', express.static(__dirname + "/libraries"));

// connect to the database using the environmental variable MONGODB_URI the value of which is stored in .env files
db.connect(process.env.MONGODB_URI)
  .then(function(){
    var server = app.listen(PORT, function(){
        console.log("Listening on port %d", server.address().port);
    });
  });

app.get('/', function(request, response){
    // generate random participant ID
    const trial_id = helper.makeCode(8);
    // determine the  browser the participant is using
    const browser = detect(request.headers['user-agent']);

    let browserOk = true;
    if (browser) {
      if (browser.mobile==true){
        browserOk = false;
      }
    }

    // evaluates to truth only if the participant is not using a mobile device
    if(browserOk){
      // generate random participant ID
      const trial_id = helper.makeCode(8);
      // determine browser the participant is using on his non-mobile device
      const browser = detect(request.headers['user-agent']);
      // use tasks.js to save the initial data
      tasks.save({
          "trial_id": trial_id,
          "study_name": study_name,
          "browser": browser,
      });

      // render the experiment, passing it the participant-unique ID generated by helper.js
      response.render('index.html', {input_data: JSON.stringify({trial_id: trial_id})});
    } else {
      // render the info message regarding the use of mobile devices for the experiment
      response.render('mobile.html');
    }
});

app.post('/data', (request, response, next) => {
  // capture the data that is stored inside request body by a new variable
  const data = request.body;
  // keep track of the participant ID
  const trial_id = request.query.trial_id || 'none';
  console.log(trial_id, 'Preparing to save trial data...');
  // use responses.js to save the survey data
  responses.save({
    trial_id: trial_id,
    study_name: study_name,
    trial_data: data,
  })
  // signal back that the survey data has successfully been saved by sending successful request status (200)
  .then(request.status(200).end());
});
